<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPza6I16\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPza6I16/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPza6I16.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPza6I16\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPza6I16\App_KernelDevDebugContainer([
    'container.build_hash' => 'Pza6I16',
    'container.build_id' => '9b475892',
    'container.build_time' => 1620241271,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPza6I16');
